import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import navStyles from "./css/nav.module.css";
import Link from "next/link";
import footerStyles from "./css/footer.module.css";
import headerStyles from "./css/header.module.css";
import Menu from "../components/menu/Menu";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className={headerStyles.header}>
          <nav className={navStyles.nav}>

          </nav>
        </header>

        <main>
          {children}
        </main>

        <footer className={footerStyles.footer}>
          <p>GSAP demo by Maria and Eddy</p>
        </footer>
      </body>
    </html>
  );
}
